word_embedding_dim: 300 # ebnerd: 1024; glove: 300
category_embedding_dim: 50
subCategory_embedding_dim: 50
cnn_method: "naive"
cnn_kernel_num: 400
cnn_window_size: 3
attention_dim: 200
long_term_masking_probability: 0.1
