category_embedding_dim: 50
subCategory_embedding_dim: 50
head_num: 20
head_dim: 20
attention_dim: 200
batch_size: 2

# MMRec specific parameters
dropout_prob: 0.1
mmrec_hidden_dim: 400
mmrec_head_num: 8
mmrec_coattention_layers: 1
